# Generated by Django 5.2.1 on 2025-08-13 13:07

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("d3c", "0001_initial"),
        ("dcim", "0207_remove_redundant_indexes"),
        ("extras", "0128_tableconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsafDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("lang", models.CharField(blank=True, max_length=20, null=True)),
                ("publisher", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CsafDocuments",
            },
        ),
        migrations.CreateModel(
            name="CsafMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=6, max_digits=6)),
                ("time", models.DateTimeField()),
                ("status", models.CharField(default="N", max_length=1)),
                ("description", models.CharField(blank=True, null=True)),
                (
                    "csaf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csaf_matches",
                        to="csaf.csafdocument",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csaf_matches",
                        to="dcim.device",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csaf_matches",
                        to="d3c.software",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CsafMatches",
            },
        ),
    ]
