# Generated by Django 5.2.1 on 2025-09-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0001_initial"),
        ("d3c", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csafmatch",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="csaf_matches",
                to="d3c.software",
            ),
        ),
    ]
