# Generated by Django 5.2.1 on 2025-08-19 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csafmatch',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='csafmatch',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
