# Generated by Django 5.2.1 on 2025-10-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0002_alter_csafmatch_software"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csafdocument",
            old_name="url",
            new_name="docurl",
        ),
    ]
