# Generated by Django 5.2.1 on 2025-10-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0003_rename_url_csafdocument_docurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csafdocument",
            name="docurl",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
