# Generated by Django 5.2.1 on 2025-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0004_alter_csafdocument_docurl"),
        ("d3c", "0002_remove_devicefinding_article_number_and_more"),
        ("dcim", "0207_remove_redundant_indexes"),
        ("extras", "0128_tableconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="csafmatch",
            name="product_name_id",
            field=models.CharField(default="unknown"),
        ),
        migrations.AddConstraint(
            model_name="csafmatch",
            constraint=models.UniqueConstraint(
                fields=("device", "software", "csaf_document", "product_name_id"),
                name="csafmatch_unique",
                nulls_distinct=False,
            ),
        ),
    ]
