# Generated by Django 5.2.1 on 2025-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0005_csafmatch_product_name_id_csafmatch_csafmatch_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csafdocument",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
