# Generated by Django 5.2.1 on 2026-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0006_alter_csafdocument_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csafdocument",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="csafmatch",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="csafmatch",
            old_name="status",
            new_name="acceptance_status",
        ),
        migrations.AddField(
            model_name="csafmatch",
            name="remediation_status",
            field=models.CharField(default="1", max_length=1),
        ),
        migrations.AlterField(
            model_name="csafmatch",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
