# Generated by Django 5.2.1 on 2026-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csaf", "0008_csafvulnerability"),
    ]

    operations = [
        migrations.AddField(
            model_name="csafdocument",
            name="product_tree",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
