# Generated by Django 5.2.1 on 2026-03-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csaf', '0010_csafmatch_module_csafvulnerability_tags_and_more'),
        ('csaf', '0010_csafvulnerability_product_ids'),
    ]

    operations = [
    ]
