# Generated by Django 5.2.1 on 2026-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csaf', '0013_csafmatchvulnerabilityremediation'),
    ]

    operations = [
        migrations.AddField(
            model_name='csafdocument',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
