# Generated by Django 5.2.1 on 2026-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csaf', '0014_csafdocument_tracking_id'),
        ('d3c', '0004_alter_filehash_options_alter_hash_options_and_more'),
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='csafmatch',
            name='csafmatch_unique',
        ),
        migrations.AddConstraint(
            model_name='csafmatch',
            constraint=models.UniqueConstraint(fields=('device', 'module', 'software', 'csaf_document', 'product_name_id'), name='csafmatch_unique', nulls_distinct=False),
        ),
    ]
