# Generated by Django 5.2.1 on 2026-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csaf', '0015_remove_csafmatch_csafmatch_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csafdocument',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

